[theme]
base = "light"
primaryColor = "#4a6b5d"
backgroundColor = "#fcfbfa"
secondaryBackgroundColor = "#f4f1eb"
textColor = "#292524"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
